# Config
config:
  mysqlHost: db-service
  mysqlPort: "3306"
  mysqlDb: breast_cancer

# Secrets
secrets:
  secretName: "mysql-secrets" 

# Images
image:
  populateDB: "miguelmendesds/breast-cancer-populate-db:latest"
  training: "miguelmendesds/breast-cancer-train:latest"
  serving: "miguelmendesds/breast-cancer-serving:latest"

# Serving
deployServing: true
serving:
  replicas: 3

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

ingress:
  host: localhost
  path: /ml/(.*)

# Cluster resources
resources:
  db:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  api:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# PVCs
persistence:
  db:
    size: "1Gi"        
  model:
    size: "1Gi"    

# Retraining schedule
retrain:
  schedule: "0 13 * * *"