apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  MYSQL_HOST: {{ .Values.config.mysqlHost | quote }}
  MYSQL_PORT: {{ .Values.config.mysqlPort | quote }}
  MYSQL_DB: {{ .Values.config.mysqlDb | quote }}