apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.model.size | quote }}