apiVersion: batch/v1
kind: CronJob
metadata:
  name: breast-cancer-retrain
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.retrain.schedule | quote }} 
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            job-name: breast-cancer-retrain
        spec:
          restartPolicy: OnFailure
          containers:
            - name: training
              image: {{ .Values.image.training }}
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: app-config
                - secretRef:
                    name: mysql-secrets
              volumeMounts:
                - name: model-storage
                  mountPath: /app/models
          volumes:
            - name: model-storage
              persistentVolumeClaim:
                claimName: model-pvc