apiVersion: batch/v1
kind: CronJob
metadata:
  name: breast-cancer-retrain
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.retrain.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            job-name: breast-cancer-retrain
        spec:
          restartPolicy: OnFailure
          containers:
            - name: training
              image: {{ .Values.image.training }}
              imagePullPolicy: Always
              env:
                - name: MYSQL_HOST
                  value: {{ .Values.config.mysqlHost }}
                - name: MYSQL_PORT
                  value: "{{ .Values.config.mysqlPort }}"
                - name: MYSQL_DB
                  value: {{ .Values.config.mysqlDb }}
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.secretName }}
                      key: MYSQL_USER
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.secretName }}
                      key: MYSQL_PASSWORD
              volumeMounts:
                - name: model-storage
                  mountPath: /app/models
          volumes:
            - name: model-storage
              persistentVolumeClaim:
                claimName: model-pvc