apiVersion: apps/v1
kind: Deployment
metadata:
  name: breast-cancer-serving
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.serving.replicas | default 3 }}
  selector:
    matchLabels:
      app: breast-cancer-serving
  template:
    metadata:
      labels:
        app: breast-cancer-serving
    spec:
      containers:
        - name: serving
          image: {{ .Values.image.serving }}
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: mysql-secrets

          volumeMounts:
            - name: model-storage
              mountPath: /app/models

          resources:
            requests:
              cpu: {{ .Values.resources.api.requests.cpu | quote }}
              memory: {{ .Values.resources.api.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.api.limits.cpu | quote }}
              memory: {{ .Values.resources.api.limits.memory | quote }}

          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-pvc